// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXgsyedsGDpJpmOVik4Mu1HjIgdQiuBdA',
    appId: '1:62713136295:web:057589d945103848884782',
    messagingSenderId: '62713136295',
    projectId: 'animehub-fc198',
    authDomain: 'animehub-fc198.firebaseapp.com',
    storageBucket: 'animehub-fc198.firebasestorage.app',
    measurementId: 'G-5T7BESZ0GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTA2HiK_VJN8YBBOklgBbNIVmhui203mw',
    appId: '1:62713136295:android:32494a2c38426229884782',
    messagingSenderId: '62713136295',
    projectId: 'animehub-fc198',
    storageBucket: 'animehub-fc198.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ4T2rLzu8M4QH_VH91NodDD1U8HXcAzc',
    appId: '1:62713136295:ios:bece89a1e0e20e2d884782',
    messagingSenderId: '62713136295',
    projectId: 'animehub-fc198',
    storageBucket: 'animehub-fc198.firebasestorage.app',
    iosClientId: '62713136295-61esvqir76puuelpol3s2h214fhb0ju1.apps.googleusercontent.com',
    iosBundleId: 'com.example.restApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ4T2rLzu8M4QH_VH91NodDD1U8HXcAzc',
    appId: '1:62713136295:ios:bece89a1e0e20e2d884782',
    messagingSenderId: '62713136295',
    projectId: 'animehub-fc198',
    storageBucket: 'animehub-fc198.firebasestorage.app',
    iosClientId: '62713136295-61esvqir76puuelpol3s2h214fhb0ju1.apps.googleusercontent.com',
    iosBundleId: 'com.example.restApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXgsyedsGDpJpmOVik4Mu1HjIgdQiuBdA',
    appId: '1:62713136295:web:99e369c2286a0de1884782',
    messagingSenderId: '62713136295',
    projectId: 'animehub-fc198',
    authDomain: 'animehub-fc198.firebaseapp.com',
    storageBucket: 'animehub-fc198.firebasestorage.app',
    measurementId: 'G-J0LJJ3QGPN',
  );
}
